[package]
name = "patternfly-yew-quickstart"
version = "0.3.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
description = "A quickstart project for using PatternFly with Yew Stack"
repository = "https://github.com/ctron/patternfly-yew-quickstart"

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
gloo-utils = "0.1"
log = "0.4"
patternfly-yew = "0.3.0"
strum = "0.24"
wasm-bindgen = "0.2"
wasm-logger = "0.2"
yew = { version = "0.20", features = ["csr"] }
yew-nested-router = "0.1.0"

[patch.crates-io]
#patternfly-yew = { path = "../patternfly-yew" }
#patternfly-yew = { git = "https://github.com/ctron/patternfly-yew", rev = "70dc7d558f6792b9077e57931a516285545b6585" } # FIXME: awaiting release
#yew-router = { git = "https://github.com/ctron/yew-router", branch="main" }
#yew-nested-router = { path = "../yew-nested-router" }
#yew-router-macro = { git = "https://github.com/ctron/yew-router", branch="main" }
#yew-router-route-parser = { git = "https://github.com/ctron/yew-router", branch="main" }
